### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by davehodg** [eea/eea.docker.graylog2#4]
I cloned your repo and did a docker-compose up. I get a log line of:

> logspout_1       | 2016/05/19 10:46:28 Graylog: write udp 172.17.0.6:12201: connection refused

Is that bad?

**Comment by ekulos** [comment]
i can't reproduce yours error, please take a look at https://github.com/eea/eea.docker.graylog2/blob/master/README.md#dependencies for a docker-compose example.
